background            #0b0a0d
foreground            #d8d1c7
cursor                 #ff6b3a
cursor_text_color      #0b0a0d
selection_background  #51484d
selection_foreground  #f2e8db
active_border_color   #ff6b3a
inactive_border_color #51484d
url_color             #d6a054
color0  #171418
color1  #c44b32
color2  #7f8b63
color3  #c78f4b
color4  #676f8f
color5  #8f637f
color6  #5f8586
color7  #c9c0b5
color8  #51484d
color9  #ff6b3a
color10 #a6b579
color11 #f0b35b
color12 #8997c7
color13 #bd85ac
color14 #78b5b8
color15 #f2e8db
